import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { query, orderBy, deleteDoc, doc } from "firebase/firestore";
import { useAuthState } from "react-firebase-hooks/auth";
import jsPDF from "jspdf";
import { Download, FileText, QrCode, Trash2 } from "lucide-react";
import QRCode from "qrcode";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { AppShell } from "@/components/app-shell";
import { EmptyState, GlassCard, SectionTitle } from "@/components/medical-ui";
import { Button } from "@/components/ui/button";
import { CardContent, CardHeader } from "@/components/ui/card";
import { getCollections, useTypedCollection, type ReportRecord } from "@/lib/db";
import { auth } from "@/lib/firebase";
import { DISCLAIMER } from "@/lib/agents/types";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Report Center — MEDGUIDE AI" },
      {
        name: "description",
        content:
          "Review and export professional clinical reports with citations, confidence and safety notes as PDF.",
      },
      { property: "og:title", content: "Report Center — MEDGUIDE AI" },
      {
        property: "og:description",
        content: "Export evidence-linked clinical reports generated by the multi-agent pipeline.",
      },
    ],
  }),
  component: ReportsPage,
});

function ReportsPage() {
  const [user] = useAuthState(auth);
  const cols = user ? getCollections(user.uid) : null;
  const [reports] = useTypedCollection<ReportRecord>(
    cols ? query(cols.reports, orderBy("createdAt", "desc")) : null,
  );

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = reports.find((r) => r.id === selectedId) ?? reports[0];

  const exportPdf = async (report: ReportRecord) => {
    const docPdf = new jsPDF({ unit: "pt", format: "a4" });
    const margin = 48;
    const width = docPdf.internal.pageSize.getWidth() - margin * 2;
    let y = margin;

    docPdf.setFontSize(16);
    docPdf.text("MEDGUIDE AI — Clinical Report", margin, y);
    y += 20;
    docPdf.setFontSize(9);
    docPdf.setTextColor(120);
    docPdf.text(`${report.title} · ${new Date(report.createdAt).toLocaleString()}`, margin, y);
    y += 22;

    docPdf.setTextColor(30);
    docPdf.setFontSize(10);
    const lines = docPdf.splitTextToSize(report.markdown.replace(/[#*`]/g, ""), width) as string[];
    for (const line of lines) {
      if (y > docPdf.internal.pageSize.getHeight() - 90) {
        docPdf.addPage();
        y = margin;
      }
      docPdf.text(line, margin, y);
      y += 13;
    }

    try {
      const qr = await QRCode.toDataURL(
        `MEDGUIDE AI report: ${report.title} (${new Date(report.createdAt).toISOString()})`,
        { margin: 1, width: 128 },
      );
      if (y > docPdf.internal.pageSize.getHeight() - 140) {
        docPdf.addPage();
        y = margin;
      }
      docPdf.addImage(qr, "PNG", margin, y + 10, 72, 72);
    } catch {
      /* QR is optional */
    }

    docPdf.setFontSize(8);
    docPdf.setTextColor(150);
    docPdf.text(DISCLAIMER, margin, docPdf.internal.pageSize.getHeight() - 30);
    docPdf.save(`${report.title.slice(0, 40).replace(/\W+/g, "-") || "clinical-report"}.pdf`);
    toast.success("PDF exported");
  };

  return (
    <AppShell
      title="Report Center"
      subtitle="Professional clinical reports with citations and confidence"
    >
      {reports.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No reports yet"
          description="Save a consultation and the Report Generator agent's output appears here, ready to export."
        />
      ) : (
        <div className="grid gap-4 lg:grid-cols-[300px_1fr]">
          <GlassCard>
            <CardHeader className="pb-2">
              <SectionTitle title="Reports" hint={`${reports.length} saved`} />
            </CardHeader>
            <CardContent className="space-y-2">
              {reports.map((r) => (
                <div
                  key={r.id}
                  className={`flex items-start gap-2 rounded-lg border p-3 transition-colors ${
                    selected?.id === r.id
                      ? "border-primary/50 bg-primary/10"
                      : "border-border/60 bg-card/40"
                  }`}
                >
                  <button
                    type="button"
                    className="min-w-0 flex-1 text-left"
                    onClick={() => setSelectedId(r.id!)}
                  >
                    <p className="truncate text-xs font-medium">{r.title}</p>
                    <p className="text-[0.65rem] text-muted-foreground">
                      {new Date(r.createdAt).toLocaleDateString()}
                    </p>
                  </button>
                  <button
                    type="button"
                    onClick={() => cols && deleteDoc(doc(cols.reports, r.id!))}
                    className="text-muted-foreground transition-colors hover:text-destructive"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </button>
                </div>
              ))}
            </CardContent>
          </GlassCard>

          {selected && (
            <GlassCard>
              <CardHeader className="pb-2">
                <SectionTitle
                  icon={FileText}
                  title={selected.title}
                  hint={new Date(selected.createdAt).toLocaleString()}
                  right={
                    <div className="flex gap-2">
                      <Button size="sm" variant="outline" onClick={() => exportPdf(selected)}>
                        <QrCode className="mr-1.5 h-4 w-4" /> PDF + QR
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => {
                          const blob = new Blob([selected.markdown], { type: "text/markdown" });
                          const url = URL.createObjectURL(blob);
                          const a = document.createElement("a");
                          a.href = url;
                          a.download = `${selected.title.slice(0, 40).replace(/\W+/g, "-")}.md`;
                          a.click();
                          URL.revokeObjectURL(url);
                        }}
                      >
                        <Download className="mr-1.5 h-4 w-4" /> Markdown
                      </Button>
                    </div>
                  }
                />
              </CardHeader>
              <CardContent>
                <div className="prose prose-sm dark:prose-invert max-w-none rounded-lg bg-card/40 p-5 border border-border/50 backdrop-blur-md leading-relaxed text-foreground prose-headings:font-display prose-headings:text-foreground prose-h1:text-xl prose-h2:text-base prose-h3:text-sm prose-p:my-2 prose-li:my-1 prose-code:text-primary prose-a:text-primary">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{selected.markdown}</ReactMarkdown>
                </div>
              </CardContent>
            </GlassCard>
          )}
        </div>
      )}
    </AppShell>
  );
}
