/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DrugsRouteImport } from './routes/drugs'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ImagingRouteImport } from './routes/imaging'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as ApiConsultRouteImport } from './routes/api/consult'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugsRoute = DrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagingRoute = ImagingRouteImport.update({
  id: '/imaging',
  path: '/imaging',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultRoute = ApiConsultRouteImport.update({
  id: '/api/consult',
  path: '/api/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/assistant/$threadId',
  path: '/assistant/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/consultation': typeof ConsultationRoute
  '/dashboard': typeof DashboardRoute
  '/drugs': typeof DrugsRoute
  '/explainability': typeof ExplainabilityRoute
  '/graph': typeof GraphRoute
  '/imaging': typeof ImagingRoute
  '/literature': typeof LiteratureRoute
  '/patient': typeof PatientRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/consult': typeof ApiConsultRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/consultation': typeof ConsultationRoute
  '/dashboard': typeof DashboardRoute
  '/drugs': typeof DrugsRoute
  '/explainability': typeof ExplainabilityRoute
  '/graph': typeof GraphRoute
  '/imaging': typeof ImagingRoute
  '/literature': typeof LiteratureRoute
  '/patient': typeof PatientRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/consult': typeof ApiConsultRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant': typeof AssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/consultation': typeof ConsultationRoute
  '/dashboard': typeof DashboardRoute
  '/drugs': typeof DrugsRoute
  '/explainability': typeof ExplainabilityRoute
  '/graph': typeof GraphRoute
  '/imaging': typeof ImagingRoute
  '/literature': typeof LiteratureRoute
  '/patient': typeof PatientRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/consult': typeof ApiConsultRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/assistant/': typeof AssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/consultation'
    | '/dashboard'
    | '/drugs'
    | '/explainability'
    | '/graph'
    | '/imaging'
    | '/literature'
    | '/patient'
    | '/pipeline'
    | '/reports'
    | '/research'
    | '/settings'
    | '/timeline'
    | '/api/assistant'
    | '/api/consult'
    | '/assistant/$threadId'
    | '/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/consultation'
    | '/dashboard'
    | '/drugs'
    | '/explainability'
    | '/graph'
    | '/imaging'
    | '/literature'
    | '/patient'
    | '/pipeline'
    | '/reports'
    | '/research'
    | '/settings'
    | '/timeline'
    | '/api/assistant'
    | '/api/consult'
    | '/assistant/$threadId'
    | '/assistant'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/consultation'
    | '/dashboard'
    | '/drugs'
    | '/explainability'
    | '/graph'
    | '/imaging'
    | '/literature'
    | '/patient'
    | '/pipeline'
    | '/reports'
    | '/research'
    | '/settings'
    | '/timeline'
    | '/api/assistant'
    | '/api/consult'
    | '/assistant/$threadId'
    | '/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  ConsultationRoute: typeof ConsultationRoute
  DashboardRoute: typeof DashboardRoute
  DrugsRoute: typeof DrugsRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  GraphRoute: typeof GraphRoute
  ImagingRoute: typeof ImagingRoute
  LiteratureRoute: typeof LiteratureRoute
  PatientRoute: typeof PatientRoute
  PipelineRoute: typeof PipelineRoute
  ReportsRoute: typeof ReportsRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiConsultRoute: typeof ApiConsultRoute
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drugs': {
      id: '/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof DrugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imaging': {
      id: '/imaging'
      path: '/imaging'
      fullPath: '/imaging'
      preLoaderRoute: typeof ImagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consult': {
      id: '/api/consult'
      path: '/api/consult'
      fullPath: '/api/consult'
      preLoaderRoute: typeof ApiConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  ConsultationRoute: ConsultationRoute,
  DashboardRoute: DashboardRoute,
  DrugsRoute: DrugsRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  GraphRoute: GraphRoute,
  ImagingRoute: ImagingRoute,
  LiteratureRoute: LiteratureRoute,
  PatientRoute: PatientRoute,
  PipelineRoute: PipelineRoute,
  ReportsRoute: ReportsRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiConsultRoute: ApiConsultRoute,
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
